language: java
jdk:
  - openjdk11
deploy:
  provider: heroku
  api_key:
    secure: thmLdi8M3P3bVfNkUXIKnvk6IKVR1BDomIFD4E4fsciCMDeR/oX2hTeWxaLdFdjBZ3d3wNzGURsiun8CnUfSHFB7cdkwGJs+ULCGi5yD+cSBhz+nhvtwqN9YNp/y8j0WmfQ2vkvxYh2podjcSbnDuakvHpgcivV4JYqNzT6YMSxw7Mdva4ohqzrop54DwYuPGjGtJzh5vgYkaH2xHAgqIK6+W3CedxrIZmDYvFCD8tqv8r4u3NyMfHXSkgp5vnXMLgTyOKdtrL2lui97R8JrhDLfKEkavR08eT8+G/8t+fTrh2Bcodxec6LUJ6ujQ5ZfHmfuLNwtwasJseHvqNNXGggOcCC/FLDAqw697p5HUNxlGmPALQ3exMSP5KYc8EDghAquulxHAH35mjt+VcOsD7yCkhNGjOAO/TzTle6d1SYe12wy01i7spdCfLuaYssGZHHXxCiGcpXZ7sn6dYiWOIDwk3VncJRb2M2dHwisXrV5j37/766G0QqLI904/85VIP20l5fc2izpfr4lgkiaCkkAaLsxuV5dsk86ZA3gp1627Q/BVmvpW9zgQsoub0WjSk0hPfflgcNjlowxYIW397G0IQeSE7PptiUEhBQXqZ2b/hNXTDJ+UZ7/5fI+l4eeKNG7KTSKDJiJC1dH+2bf7UtZYSXYYXpapEpndCpm0p0=
  app: selfstorage
after_success:
  - mvn clean cobertura:cobertura coveralls:report
